language = "C"
include_version = true
header = """\
#ifndef CURP_VERIFIER_H
#define CURP_VERIFIER_H

#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif
"""

trailer = """\
#ifdef __cplusplus
}
#endif

#endif // CURP_VERIFIER_H
"""